---
- name: Prepare Windows endpoints to generate OpenSCAP report
  hosts: "{{ target |default('windows') }}"
  tasks:
    - name: Download Windows OpenSCAP profile
      ansible.windows.win_get_url:
        url: "{{ scap_profile_url }}"
        dest: "{{ scap_profile_location }}"
    
    - name: Unpack Windows OpenSCAP profile
      community.windows.win_unzip:
        src: "{{ scap_profile_location }}"
        dest: "{{ scap_profile_working_dir }}"
        creates: "{{ scap_profile_working_dir }}"

    - name: Install OpenSCAP 
      ansible.windows.win_package:
        path: "{{ scap_installer_url }}"
        arguments:
        - /q

    # fixes error where oscap will not launch, may not be needed in your environment
    - name: Install VC_redist.x86.exe (dll fix for oscap)
      ansible.windows.win_package:
        path: https://aka.ms/vs/15/release/VC_redist.x86.exe
        arguments:
        - /S

    - name: Ensure OpenSCAP is in $env:PATH
      ansible.windows.win_path:
        elements: C:\Program Files (x86)\OpenSCAP 1.3.4 # change as needed
        scope: machine
        state: present

    - name: run OpenSCAP
      ansible.windows.win_shell: |
        oscap xccdf eval --report ..\{{ scap_report_name }} \
        --profile xccdf_mil.disa.stig_profile_Disable_Slow_Rules \
        "{{ scap_profile_xml }}"          
      args:
        chdir: "{{ scap_profile_working_dir }}" 
      ignore_errors: yes
      tags: report


