---
- name: Prepare RHEL endpoints to generate OpenSCAP report
  hosts: "{{ target |default('rhel') }}"
  tasks: 
    - name: Install OpenSCAP
      ansible.builtin.package:
        name:
          - openscap-utils
          - scap-security-guide
        state: present
      become: yes

    - name: run OpenSCAP
      ansible.builtin.shell: |
        oscap xccdf eval --report ..\{{ scap_report_name }} \
        --profile {{scap_profile_title}} \
        "{{ scap_profile_xml }}"          
      args:
        chdir: "{{ scap_profile_working_dir }}" 
      ignore_errors: yes
      tags: report




         